#!/bin/bash

# Быстрый деплой на сервер - скопируйте команды и выполните на сервере

echo "=== БЫСТРЫЙ ДЕПЛОЙ НЕЙРОМАГИИ ==="
echo ""
echo "Скопируйте и выполните эти команды на сервере:"
echo ""
echo "# 1. Подключаемся к серверу"
echo "ssh root@138.124.15.60"
echo ""
echo "# 2. Устанавливаем Docker"
echo "curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh && rm get-docker.sh"
echo ""
echo "# 3. Устанавливаем Docker Compose"
echo "curl -L \"https://github.com/docker/compose/releases/latest/download/docker-compose-\$(uname -s)-\$(uname -m)\" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose"
echo ""
echo "# 4. Устанавливаем Git"
echo "apt install git -y"
echo ""
echo "# 5. Клонируем проект"
echo "mkdir -p /opt/neuromagic && cd /opt/neuromagic && git clone https://github.com/Starlight19973/magic_ai.git ."
echo ""
echo "# 6. Создаём .env файл"
echo "cat > .env << 'EOF'"
echo "SECRET_KEY=prod_secret_key_2024_neuromagic_ultra_secure"
echo "TELEGRAM_BOT_TOKEN=8528801413:AAFW7dH8I-soM2m_6cUC_HZGIf_DnDEtbYQ"
echo "TELEGRAM_CHAT_ID=-5020049520"
echo "EOF"
echo ""
echo "# 7. Создаём директории"
echo "mkdir -p data logs nginx/ssl"
echo ""
echo "# 8. Собираем и запускаем"
echo "docker-compose build --no-cache"
echo "docker-compose run --rm app python -c \"from app.database import init_db; import asyncio; asyncio.run(init_db())\""
echo "docker-compose run --rm app python create_test_user.py"
echo "docker-compose --profile production up -d"
echo ""
echo "# 9. Проверяем"
echo "docker-compose ps"
echo "docker-compose logs -f"
echo ""
echo "=== ГОТОВО! Сайт доступен на http://138.124.15.60 ==="

